### ISSUE TITLE
add topojson utilities

### ISSUE THREAD

**Issue by sckott** [ropensci/geojsonio#100]

**Comment by sckott** [comment]
work on branch https://github.com/ropensci/geojsonio/tree/topojson-write

**Comment by jeroenooms** [comment]
The `geo2topo` function gives different output from the command line utility. This is what the npm module gives:

```sh
jeroen$ echo '{"type": "LineString", "coordinates": [ [100.0, 0.0], [101.0, 1.0] ]}' | ./geo2topo
```
```json
{"type":"Topology","objects":{"-":{"type":"LineString","arcs":[0]}},"arcs":[[[100,0],[101,1]]],"bbox":[100,0,101,1]}
```

And this is what the R function gives:

```r
x <- '{"type": "LineString", "coordinates": [ [100.0, 0.0], [101.0, 1.0] ]}'
cat(geo2topo(x))
```
```json
{"type":"Topology","objects":{"type":"LineString","coordinates":[[100,0],[101,1]]},"arcs":[]}
```

**Comment by sckott** [comment]
yeah, i guess that makes sense, since https://github.com/topojson/topojson-server/blob/v2.0.0/bin/geo2topo is doing other things before the `topojson.topology` call https://github.com/topojson/topojson-server/blob/v2.0.0/bin/geo2topo#L113 - i guess I mistakingly thought `topojson.topology` would be adequate

**Comment by sckott** [comment]
hmmm, @jeroenooms any thoughts on how to get the same answer using `topojson.topology` as the `geo2topo` command line option ?
