### ISSUE TITLE
cran checks failing

### ISSUE THREAD

**Issue by sckott** [ropensci/geojsonio#103]
> See https://cran.r-project.org/web/checks/check_results_geojsonio.html .

> The latest sf update broke geojsonio on Fedora 24, which reports

> Linking to GEOS 3.5.0, GDAL 2.0.2, proj.4 4.9.2

> Edzer may know why the o/p is different, but you really, really should
not be testing messages from other packages in your own package.  You
should also be using Suggests: packages conditionally, as on Windows 3.2.x.

**Comment by sckott** [comment]
@ateucher if you have any insight, need to submit patch soon

**Comment by sckott** [comment]
edzer said 

> and indicate that geojsonio is checking the output of GDAL functions;
the outputs indicate there is nothing wrong, but that the test is wrong
(checks identical strings, rather than strings indicating the same
datum). But I agree, it's not a geojsonio issue.

**Comment by sckott** [comment]
for the problem _should also be using Suggests: packages conditionally, as on Windows 3.2.x._

> See the manual, §1.1.3.1

**Comment by ateucher** [comment]
@edzer what is the best way to compare CRS without comparing proj4strings directly? It's something I've never been able to figure out.

**Comment by ateucher** [comment]
Interesting point about using a package conditionally in tests. I've never done that

**Comment by sckott** [comment]
@ateucher maybe we should just `skip_on_cran()` for those CRS comparison tests for now? until sorted out?

**Comment by ateucher** [comment]
Totally fine with me

**Comment by sckott** [comment]
@ateucher you can see that the `units` pkg is not avail. in this fedora build https://builder.r-hub.io/status/geojsonio_0.3.0.tar.gz-38868a445eb646cf9ff14eaf717a5b5d#L2003 not sure why

**Comment by sckott** [comment]
failure on fedora - sent a PR to gabor https://github.com/r-hub/sysreqsdb/pull/21 - so we should be able to test on fedora via rhub soon

**Comment by ateucher** [comment]
Awesome thanks for looking after that @sckott.

**Comment by edzer** [comment]
`sf` has an `==` method for `crs` objects, but even that is not bullet proof for this case:
```R
> st_crs("+proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs") == st_crs("+proj=longlat +datum=WGS84 +no_defs")
[1] FALSE
```
my (and Brian's) advice is to not add tests involving proj4 string in geojsonio, as it is variability in PROJ.4 and GDAL that you're testing, and that is not geojsonio's problem.

**Comment by ateucher** [comment]
Thanks @edzer that's helpful. @sckott maybe we could just check the first one or two coordinates to make sure they 'look like' lat/long (i.e. -360 <= x <= 360) to ensure conversion occurred?

I'm away all weekend without a computer, @sckott are you able to take care of it?

**Comment by sckott** [comment]
Sure, can try that, should be able to take care of it today

**Comment by ateucher** [comment]
Awesome, thanks Scott!

**Comment by sckott** [comment]
submitting now
