### ISSUE TITLE
geojsonio broken, certainly with GDAL >= 2.2

### ISSUE THREAD

**Issue by rsbivand** [ropensci/geojsonio#108]
A fresh rgdal is being submitted to CRAN. With GDAL 2.2.0 and later, it shows testthat failures:

geojsonio fails predictably for GDAL > 2.1, because of:

> Starting with GDAL 2.2, the layer name is built with the following logic:
> 
>     If a "name" member is found at the FeatureCollection level, it is used.
>     Otherwise if the filename is regular (ie not a URL with query parameters), then the filename without extension and path is used as the layer name.
>     Otherwise OGRGeoJSON is used.

on the help [page](http://www.gdal.org/drv_geojson.html).

```
> library(rgdal)
Loading required package: sp
rgdal: version: 1.2-8, (SVN revision 663)
 Geospatial Data Abstraction Library extensions to R successfully loaded
 Loaded GDAL runtime: GDAL 2.2.0, released 2017/04/28
 Path to GDAL shared files: /usr/local/share/gdal
 Loaded PROJ.4 runtime: Rel. 4.9.3, 15 August 2016, [PJ_VERSION: 493]
 Path to PROJ.4 shared files: (autodetected)
 Linking to sp version: 1.2-5 
> library(geojsonio)
```

See:

```
  library('sp')
  poly1 <- Polygons(list(Polygon(cbind(c(-100,-90,-85,-100),
     c(40,50,45,40)))), "1")
  poly2 <- Polygons(list(Polygon(cbind(c(-90,-80,-75,-90),
     c(30,40,35,30)))), "2")
  sp_poly <- SpatialPolygons(list(poly1, poly2), 1:2)
  tf2 <- tempfile(fileext = ".geojson")
  e <- suppressMessages(geojson_write(sp_poly, file = tf2))
  expect_is(e, "geojson")
  expect_is(unclass(e), "list")
  expect_is(as.json(e, verbose = FALSE), "json")
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer
> traceback()
11: ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv, 
        swapAxisOrder = swapAxisOrder, require_geomType = require_geomType)
10: withCallingHandlers(expr, message = function(c) invokeRestart("muffleMessage"))
9: suppressMessages(ogr_info <- ogrInfo(dsn = dsn, layer = layer, 
       encoding = encoding, use_iconv = use_iconv, swapAxisOrder = swapAxisOrder, 
       require_geomType = require_geomType))
8: readOGR(x$path, "OGRGeoJSON", ...)
7: as.SpatialPolygonsDataFrame.geojson(x, ...)
6: as.SpatialPolygonsDataFrame(x, ...)
5: as.json.geojson(e, verbose = FALSE)
4: as.json(e, verbose = FALSE)
3: paste(class(x), collapse = "/")
2: klass(object)
1: expect_is(as.json(e, verbose = FALSE), "json")
> as.json(e)
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open layer
> traceback()
8: ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv, 
       swapAxisOrder = swapAxisOrder, require_geomType = require_geomType)
7: withCallingHandlers(expr, message = function(c) invokeRestart("muffleMessage"))
6: suppressMessages(ogr_info <- ogrInfo(dsn = dsn, layer = layer, 
       encoding = encoding, use_iconv = use_iconv, swapAxisOrder = swapAxisOrder, 
       require_geomType = require_geomType))
5: readOGR(x$path, "OGRGeoJSON", ...)
4: as.SpatialPolygonsDataFrame.geojson(x, ...)
3: as.SpatialPolygonsDataFrame(x, ...)
2: as.json.geojson(e)
1: as.json(e)
> ogrInfo(e$path, "OGRGeoJSON")
Error in ogrInfo(e$path, "OGRGeoJSON") : Cannot open layer
> ogrListLayers(e$path)
[1] "file143f2e4d289a"
attr(,"driver")
[1] "GeoJSON"
attr(,"nlayers")
[1] 1
> ogrInfo(e$path)
Source: "/tmp/Rtmp204YHu/file143f2e4d289a.geojson", layer: "file143f2e4d289a"
Driver: GeoJSON; number of rows: 2 
Feature type: wkbPolygon with 2 dimensions
Extent: (-100 30) - (-75 50)
CRS: +proj=longlat +datum=WGS84 +no_defs  
Number of fields: 1 
   name type length typeName
1 dummy    2      0     Real
> ogrInfo(e$path, "file143f2e4d289a")
Source: "/tmp/Rtmp204YHu/file143f2e4d289a.geojson", layer: "file143f2e4d289a"
Driver: GeoJSON; number of rows: 2 
Feature type: wkbPolygon with 2 dimensions
Extent: (-100 30) - (-75 50)
CRS: +proj=longlat +datum=WGS84 +no_defs  
Number of fields: 1 
   name type length typeName
1 dummy    2      0     Real
```
Other failures are:

>   testthat results ================================================================
>   OK: 369 SKIPPED: 28 FAILED: 10
>   1.  Error: as.json works with geojson class inputs (@test-as.json.R#25) 
>   2.  Error: as.json works with file name inputs (@test-as.json.R#60) 
>   3.  Failure: geojson_write: convert_wgs84 works with Spatial classes (@test-crs_convert.R#138) 
>   4.  Failure: geojson_write: convert_wgs84 works with Spatial classes (@test-crs_convert.R#140) 
>   5.  Failure: geojson_write: convert_wgs84 works with Spatial classes (@test-crs_convert.R#143) 
>   6.  Failure: geojson_write: convert_wgs84 works with Spatial classes (@test-crs_convert.R#147) 
>   7.  Failure: geojson_write: convert_wgs84 works with sf classes (@test-crs_convert.R#152) 
>   8.  Failure: geojson_write: convert_wgs84 works with sf classes (@test-crs_convert.R#154) 
>   9.  Failure: geojson_write: convert_wgs84 works with sf classes (@test-crs_convert.R#157) 
>   10. Failure: geojson_write: convert_wgs84 works with sf classes (@test-crs_convert.R#161)

**Comment by sckott** [comment]
Thanks for this. Will fix asap.

**Comment by rsbivand** [comment]
If you don't have a GDAL 2.2.0 or 2.2.1 (just released), please let me know and I'll check if I can.

**Comment by sckott** [comment]
I think we're good now, @ateucher let me know if you find any problems due to this fix

**Comment by ateucher** [comment]
Makes sense to me, though could we use `readOGR(x$path, rgdal::ogrListLayers(x$path)[[1]], ...)` instead and not have to check the gdal version?

On my Windows machine with GDAL 2.0.1:

``` r
rgdal::ogrListLayers("inst/examples/california.geojson")
#> [1] "OGRGeoJSON"
#> attr(,"driver")
#> [1] "GeoJSON"
#> attr(,"nlayers")
#> [1] 1
rgdal::getGDALVersionInfo()
#> [1] "GDAL 2.0.1, released 2015/09/15"
```

As we do [here](https://github.com/ropensci/geojsonio/blob/cbcbed42d97e8219ce1d8b908b3ebed3873e213b/R/file_to_geojson.r#L126)?

With GDAL >= 2.2 I would expect `rgdal::ogrListLayers("inst/examples/california.geojson")` to return `"california"` but would need to check...

**Comment by sckott** [comment]
Hmm, i don't know - can check that

**Comment by ateucher** [comment]
I get this on my mac with GDAL v2.2.0:

``` r
rgdal::getGDALVersionInfo()
#> [1] "GDAL 2.2.0, released 2017/04/28"
rgdal::ogrListLayers(system.file("examples", "california.geojson", package = "geojsonio"))
#> [1] "california"
#> attr(,"driver")
#> [1] "GeoJSON"
#> attr(,"nlayers")
#> [1] 1
```

So I think that could work... thoughts?

**Comment by ateucher** [comment]
@sckott I pushed branch `read-gdal2` with this method implemented - let me know what you think

**Comment by sckott** [comment]
will have a look

**Comment by sckott** [comment]
@ateucher tested out on newer and older gdal, works good, merge when you're ready

**Comment by ateucher** [comment]
Great, will do - thanks!

**Comment by MedhatAhmed** [comment]
I'm trying to run this piece of code 
url <- "http://leafletjs.com/examples/choropleth/us-states.js"
url.exists(url)
states <- geojsonio::geojson_read(url, what="sp")
and I got an error saying "Error in rgdal::ogrListLayers(input) : Cannot open data source"
