### ISSUE TITLE
Timeout when trying to read a simple GeoJSON file

### ISSUE THREAD

**Issue by miradimi** [ropensci/geojsonio#115]
This very simple command:

dat <- geojsonio::geojson_read(myfile)

generates this error for me:
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

I validated the input file using http://geojsonlint.com/ 

Session info ----------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, darwin13.4.0        
 ui       AQUA                        
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Denver              
 date     2017-08-03                  

Packages --------------------------------------------------------------------------------------------------------------------------------------------
 package       * version    date       source          
 base          * 3.3.2      2016-10-31 local           
 colorspace      1.3-2      2016-12-14 CRAN (R 3.3.2)  
 curl            2.8.1      2017-07-21 CRAN (R 3.3.2)  
 datasets      * 3.3.2      2016-10-31 local           
 devtools      * 1.13.3     2017-08-02 CRAN (R 3.3.2)  
 digest          0.6.12     2017-01-27 CRAN (R 3.3.2)  
 foreign         0.8-68     2017-04-24 CRAN (R 3.3.2)  
 geojsonio     * 0.3.8      2017-07-24 CRAN (R 3.3.2)  
 geojsonrewind * 0.0.1.9300 2017-07-25 local (@0.0.1.9)
 ggplot2         2.2.1      2016-12-30 CRAN (R 3.3.2)  
 git2r           0.18.0     2017-01-01 CRAN (R 3.3.2)  
 graphics      * 3.3.2      2016-10-31 local           
 grDevices     * 3.3.2      2016-10-31 local           
 grid            3.3.2      2016-10-31 local           
 gtable          0.2.0      2016-02-26 CRAN (R 3.3.0)  
 httr            1.2.1      2016-07-03 CRAN (R 3.3.0)  
 jsonlite        1.5        2017-06-01 CRAN (R 3.3.2)  
 knitr           1.16       2017-05-18 CRAN (R 3.3.2)  
 lattice         0.20-35    2017-03-25 CRAN (R 3.3.2)  
 lawn          * 0.3.7.9113 2017-07-27 local (@0.3.7.9)
 lazyeval        0.2.0      2016-06-12 CRAN (R 3.3.0)  
 magrittr        1.5        2014-11-22 CRAN (R 3.3.0)  
 maptools        0.9-2      2017-03-25 CRAN (R 3.3.2)  
 memoise         1.1.0      2017-04-21 CRAN (R 3.3.2)  
 methods       * 3.3.2      2016-10-31 local           
 mime            0.5        2016-07-07 CRAN (R 3.3.0)  
 munsell         0.4.3      2016-02-13 CRAN (R 3.3.0)  
 plyr          * 1.8.4      2016-06-08 CRAN (R 3.3.0)  
 proj4         * 1.0-8      2012-08-05 CRAN (R 3.3.0)  
 R6              2.2.1      2017-05-10 CRAN (R 3.3.2)  
 Rcpp            0.12.11    2017-05-22 CRAN (R 3.3.2)  
 rgdal         * 1.2-7      2017-04-25 CRAN (R 3.3.2)  
 rgeos           0.3-23     2017-04-06 CRAN (R 3.3.2)  
 rlang           0.1.1      2017-05-18 CRAN (R 3.3.2)  
 rstudioapi      0.6        2016-06-27 CRAN (R 3.3.0)  
 scales          0.4.1      2016-11-09 CRAN (R 3.3.2)  
 sp            * 1.2-5      2017-06-29 CRAN (R 3.3.2)  
 stats         * 3.3.2      2016-10-31 local           
 tibble          1.3.3      2017-05-28 CRAN (R 3.3.2)  
 tools           3.3.2      2016-10-31 local           
 utils         * 3.3.2      2016-10-31 local           
 V8              1.5        2017-04-25 CRAN (R 3.3.2)  
 withr           1.0.2      2016-06-20 CRAN (R 3.3.0)  
>

**Comment by sckott** [comment]
thanks @miradimi but we need the value of `myfile` to replicate the problem - or at least a similar file that creates the same error

**Comment by miradimi** [comment]
HI Scott, 

I’ll have to construct a new file as I can’t release any data without prior approval.  I’ll try and do that tomorrow but I don’t know 
if I can get to it. If you need to close the ticket because of incomplete data, please do so. I am happy to re-open it.

Mira

**Comment by sckott** [comment]
okay, understandable. will leave it open for now

you can email it to me if you want, i promise i won't share it. 

fyi, we have a geojson lint pkg https://cran.rstudio.com/web/packages/geojsonlint/

**Comment by miradimi** [comment]
Hi Scott,  now I remember. I got to your package because I wanted to use the capability
to change the winding order of my input file. So when I test my input file using a regular
JSON validator I get no errors. But I do get an error when I try to validate with your
GeoJSON linter saying that the winding order is incorrect.  Could my problem in the
command:

dat <- geojsonio::geojson_read( file) 

originate from the winding error? If so, then how would I use your turf/lawn packages?

Mira

**Comment by sckott** [comment]
Possibly. hard to tell without seeing the data. Though the error you gave in your first comment on this issue doesn't suggest that that's the problem

**Comment by miradimi** [comment]
I’ll send you a file tomorrow with data in the wrong winding order for you to try out.  That’s also the file that gave me the error I reported.

Mira

**Comment by sckott** [comment]
thanks.

**Comment by miradimi** [comment]
Hi Scott,

Attached is a mini-file that behaves the way I described:

1. No problems in a regular JSON validator (https://jsonformatter.curiousconcept.com/ <https://jsonformatter.curiousconcept.com/> and https://www.freeformatter.com/json-validator.html <https://www.freeformatter.com/json-validator.html>)

2. waring/error in http://geojsonlint.com/ <http://geojsonlint.com/>
Line 10: Polygons and MultiPolygons should follow the right-hand rule
Line 44: Polygons and MultiPolygons should follow the right-hand rule
Line 78: Polygons and MultiPolygons should follow the right-hand rule

3. ingest with geojsonio (v0.3.8)
gdat <- geojsonio::geojson_read( "test_geojsonio.json") 
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
> 


Thanks, Mira

**Comment by sckott** [comment]
hi @miradimi no attachment came through

**Comment by sckott** [comment]
Hi @miradimi - I can't replicate your problem with the files you sent. 

I did notice something that you can try though. The default for the `method` parameter in `geojson_read` is `method = "web"` - which goes out to and uses http://ogre.adc4gis.com/convert - you can try setting `method = "local"` which will then use  `rgdal` instead - `method = "web"` is consistent with the error you see as `curl` is the underlying pkg doing http requests to the web

**Comment by sckott** [comment]
let me know if that works or not

**Comment by miradimi** [comment]
Hi Scott,  

This works for fixing the 
mydat<-geojsonio::geojson_read(...) error I got (thank you!). I can also execute the
mydat2<-lawn::lawn_rewind( mydat) function and validate the output using 
geojsonio::validate( mydat2).  

Now, the output of lawn_rewind is an object of type "featurecollection" that I would like to print to file. I didn't see a print option in the lawn package and in order to use your geojsonio::geojson_write I need to convert the object to a data type that geojsonio::geojson_write accepts.  To solve that last step can you point me in the right direction?

Many thanks for your help!
Mira

**Comment by sckott** [comment]
hi @miradimi - so this works, but not ideal i guess

```r
x <- geojsonio::geojson_read("~/Downloads/test_geojsonio.json")
xx <- lawn::lawn_rewind(x) 
geojsonio::geojson_write(jsonlite::toJSON(unclass(xx), auto_unbox = TRUE))
```

**Comment by miradimi** [comment]
This works indeed! Thanks, Scott.

**Comment by sckott** [comment]
great, glad it worked. don't hesitate to ask if you have other problems

**Comment by miradimi** [comment]
Thanks again for all the help!

Cheers, Mira
