### ISSUE TITLE
Web Connection

### ISSUE THREAD

**Issue by r-barnes** [ropensci/geojsonio#118]
geojsonio tries to connect to a website when the library is loaded.

I'm even able to log the traffic:

      PID USER     PROGRAM                           DEV        SENT      RECEIVED       
    24257 user     /usr/lib/R/bin/exec/R             enp0s2      1.836      11.718 KB
     2512 user     /opt/google/chrome/chrome         enp0s2      5.651      10.367 KB
     2140 user     /usr/lib/thunderbird/thunderbird  enp0s2      4.028       4.442 KB
        ? root     unknown TCP                                   0.000       0.000 KB

There are two problems with this.

1. The library loads slowly as a result.

2. I cannot get the library to load at all when I don't have an internet connection.

Combined these make geojsonio practically useless to me and impossible to use as a component of any other package. Which is a shame because geojsonio other seems quite useful and I was excited to find it!

I hope there's a way to make this internet connection business optional.

**Comment by sckott** [comment]
We were loading topojson JS lib from the web - which we didn't need to do, should be fixed now, install `devtools::install_github("ropensci/geojsonio")` and try again

**Comment by r-barnes** [comment]
I tested again and didn't see any traffic this time. That's 100% better!

**Comment by sckott** [comment]
glad it works
