### ISSUE TITLE
Topojson write also writes a GeoJSON

### ISSUE THREAD

**Issue by martgnz** [ropensci/geojsonio#127]
While using `topojson_write` I've noticed that it also writes a GeoJSON file with the same name and the `.geojson` extension. Is this expected? Or am I doing something wrong? 

This is my code:
```r
> topojson_write(df, file = "df.json", geometry='polygon', group="group")
Success! File at df.json
<topojson-file>
  Path:       df.json
  From class: data.frame
```

**Comment by sckott** [comment]
thx @martgnz , can you reinstall `devtools::install_github("ropensci/geojsonio")` and try again

**Comment by martgnz** [comment]
Now it works as expected, thank you 👍
