### ISSUE TITLE
geojson_sp fails with new rgdal

### ISSUE THREAD

**Issue by ateucher** [ropensci/geojsonio#130]
This is a big one @sckott. 

We rely on an undocumented "feature" of `rgdal::readOGR()` where it will happily read a geojson character string passed to the `dsn` argument ([here](https://github.com/ropensci/geojsonio/blob/0efc4e32fcf95475f28b9de419dd1efebc0b58b0/R/geojson_sp.R#L75-L78)). `sf::st_read()` does the same.

A recent change to **rgdal** in v1.2-18 (now on CRAN) is causing this to fail. The change is the addition of `normalizePath(dsn)` [here](https://github.com/cran/rgdal/blob/16ed5969b00a790e1aaaceb2d7a3e0d30e777aac/R/ogr_sp.R#L14), so any geojson string longer than a valid file path gets truncated and thus not read. (And even a short enough string will throw warnings).

I think the easiest solution would be to ask Roger if he would add a conditional `if (file.exists(dsn))` as [**sf** does](https://github.com/r-spatial/sf/blob/6848cb933df662c79ee712ab46a80fe3464fb92f/R/read.R#L81-L82). I.e., replace line 14:

```r
dsn <- enc2utf8(normalizePath(dsn))
```

with:

```r
if (file.exists(dsn))
    dsn <- enc2utf8(normalizePath(dsn))
```

I think this would work.

The other option would be to skip `readOGR` and use `as(sf::st_read(geojson_string), "Spatial")`.

What do you think?

**Comment by ateucher** [comment]
PS. Our tests aren't failing because the geojson strings we use to test are short enough that they don't make `normalizePath()` fail... but they do throw warnings.

**Comment by sckott** [comment]
Good catch. I did notice new warnings, but I guess I didn't realize the impact. 

I kinda like the sf solution, but 

```r
x='{"type":"Point","coordinates":[-99.74,32.45]}"'
sf::as_Spatial(sf::st_read(x))
#> Reading layer `OGRGeoJSON' from data source `{"type":"Point","coordinates":[-99.74,32.45]}"' using driver `GeoJSON'
#> Simple feature collection with 1 feature and 0 fields
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: -99.74 ymin: 32.45 xmax: -99.74 ymax: 32.45
#> epsg (SRID):    4326
#> proj4string:    +proj=longlat +datum=WGS84 +no_defs
#> Error in sf::as_Spatial(sf::st_read(x)) :
#>   conversion from feature type sf to sp is not supported
```

but i have sf `v0.6.0`, couldn't get `v0.6.1` installed. maybe you did?

**Comment by ateucher** [comment]
Yeah strangely `as_Spatial()` doesn’t work on `sf` objects, you have to use `as(x, “Spatial”)`.  

It probably warrants a little bit more testing - in my brief experiments I noticed that the results weren’t exactly identical; possibly differences in attributes? I wonder if there are any performance implications (good or bad - It means two conversions instead of one but `st_read` tends to be faster than `readOGR`)? 

I think I’ll still ask Roger about this because I doubt we’re the only ones who depend on this behaviour of `readOGR`

**Comment by sckott** [comment]
Okay, thanks @ateucher - on vacation-ish today, so thanks for handling

**Comment by ateucher** [comment]
See below. It is actually quite a bit faster going via `sf::st_read()`. There is a slight difference in the returned `Spatial` object in that the IDs of the polygons are different. Though I don't know if that matters?

``` r
library(sf)
#> Linking to GEOS 3.6.2, GDAL 2.2.3, proj.4 5.0.0
library(rgdal) # locally built with the `if (file.exists(dsn))` catch mentioned above
#> Loading required package: sp
#> rgdal: version: 1.2-18, (SVN revision 718)
#>  Geospatial Data Abstraction Library extensions to R successfully loaded
#>  Loaded GDAL runtime: GDAL 2.2.3, released 2017/11/20
#>  Path to GDAL shared files: /usr/local/Cellar/gdal2/2.2.3/share/gdal
#>  GDAL binary built with GEOS: TRUE 
#>  Loaded PROJ.4 runtime: Rel. 5.0.0, March 1st, 2018, [PJ_VERSION: 500]
#>  Path to PROJ.4 shared files: (autodetected)
#>  Linking to sp version: 1.2-7
library(geojsonio)
#> 
#> Attaching package: 'geojsonio'
#> The following object is masked from 'package:base':
#> 
#>     pretty
library(bcmaps)
bcjs <- geojson_json(bc_bound())

system.time(bcsp_sf <- as(st_read(bcjs, quiet = TRUE), "Spatial"))
#>    user  system elapsed 
#>   0.086   0.006   0.092
system.time(bcsp_sp <- rgdal::readOGR(bcjs, "OGRGeoJSON", verbose = FALSE))
#>    user  system elapsed 
#>   0.423   0.005   0.429

all.equal(bcsp_sf, bcsp_sp)
#>   [1] "Attributes: < Component \"data\": Attributes: < Component \"row.names\": Mean relative difference: 0.01315789 > >"
#>   [2] "Attributes: < Component \"polygons\": Component 1: Attributes: < Component 4: 1 string mismatch > >"              
#>   [3] "Attributes: < Component \"polygons\": Component 2: Attributes: < Component 4: 1 string mismatch > >"              
#>   [4] "Attributes: < Component \"polygons\": Component 3: Attributes: < Component 4: 1 string mismatch > >"              
#>   [5] "Attributes: < Component \"polygons\": Component 4: Attributes: < Component 4: 1 string mismatch > >"              
#>   [6] "Attributes: < Component \"polygons\": Component 5: Attributes: < Component 4: 1 string mismatch > >"              
#>   [7] "Attributes: < Component \"polygons\": Component 6: Attributes: < Component 4: 1 string mismatch > >"              
#>   [8] "Attributes: < Component \"polygons\": Component 7: Attributes: < Component 4: 1 string mismatch > >"              
#>   [9] "Attributes: < Component \"polygons\": Component 8: Attributes: < Component 4: 1 string mismatch > >"              
#>  [10] "Attributes: < Component \"polygons\": Component 9: Attributes: < Component 4: 1 string mismatch > >"              
#> .... and so on

# The difference is in the IDs of the polygons: coming via sf they are 1-based, 
# via sp they are 0-based
bcsp_sf@polygons[[1]]@ID
#> [1] "1"
bcsp_sp@polygons[[1]]@ID
#> [1] "0"

all.equal(bcsp_sf, bcsp_sp, check.attributes = FALSE)
#> [1] TRUE
```

Created on 2018-03-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by ateucher** [comment]
I've implemented the sf route in the `fix-geojson_sp` branch. I also moved `sf` from `Suggests` to `Imports`, which I think is warranted if we go this route.
