### ISSUE TITLE
Update dependency list for ubuntu 17.10

### ISSUE THREAD

**Issue by diegopenhanut** [ropensci/geojsonio#134]
I did need to install `libgdal-dev` `libgeos-c1v5` `libproj-dev` `libv8-dev` `libjq-dev` on ubuntu budgie 17.10 to get geojsonio to work. Maybe it is worth to put this info on the readme file.

**Comment by sckott** [comment]
thanks for this @diegopenhanut 

Do you mean for the current version on CRAN? or did you install from github?

**Comment by ateucher** [comment]
Since those are are system dependencies for R packages that `geojsonio` depends on (`sf`, `sp`, `rgdal`, `rgeos`, `jqr`, `V8`) rather than ones that `geojsonio` relies on directly, I wonder how much responsibility we should take on here regarding getting them installed? it's a constantly moving target. Instead could we point to installation instructions for those packages (eg., https://github.com/r-spatial/sf#installing)?

**Comment by sckott** [comment]
right, maybe its best to direct users to the install instructions for other pkgs that depend on those libs - if they exists that is - if not, then maybe we should include them

**Comment by florianm** [comment]
I'm currently stuck with 
```
hecking geos: linking with libgeos_c... no
/usr/bin/ld: cannot find -lgeos
collect2: error: ld returned 1 exit status
configure: Install failure: compilation and/or linkage problems.
configure: error: initGEOS_r not found in libgeos_c.
ERROR: configuration failed for package ‘rgeos’
```

on Ubuntu 16.04.5 LTS with R 3.4 following geojsonio install instructions.
Even after following https://github.com/r-spatial/sf#installing I still get `/usr/bin/ld: cannot find -lgeos
` on both package and source install of rgeos. I haven't got a working install process yet for rgeos.

**Comment by sckott** [comment]
thanks @florianm for the report. will have a look my tomorrow

**Comment by sckott** [comment]
@florianm does this https://stat.ethz.ch/pipermail/r-sig-geo/2018-October/026947.html  help at all?

**Comment by sckott** [comment]
or maybe this https://stackoverflow.com/questions/53042751/when-trying-to-install-rgeos-r-cannot-find-lgeos

**Comment by florianm** [comment]
Bugger, I'm in the middle of a dist upgrade to Ubuntu 18.04, of course I can't install the recommended `sudo apt install libgeos++-dev` but will try once upgraded!

**Comment by florianm** [comment]
@sckott on Ubuntu 18.04 LTS following your advice, this works:
```
sudo apt install libgeos++-dev
install.packages("rgeos", type = "source")
devtools::install_github("ropensci/geojsonio")
```
Cheers!

**Comment by sckott** [comment]
great, thanks, i'll add that to readme
