### ISSUE TITLE
geojsonio seems vulnerable to PROJ 6

### ISSUE THREAD

**Issue by rsbivand** [ropensci/geojsonio#148]
I'm running reverse dependency checks using **sf** from github adapted not to fail with PROJ 6 sf_0.7-4, and CRAN **rgdal** also adapted not to fail with PROJ 6 rgdal_1.4-3, but see that **geojsonio** fails with PROJ 6. The failures are deep inside testthat, so opaque. I attach the compressed R CMD check files (R 3.5.3).
[failing_check.zip](https://github.com/ropensci/geojsonio/files/3111208/failing_check.zip).

Could you please check on a system instance with PROJ 6? When PROJ 7 hits us in 10 months, **sf** and **rgdal** will follow, while trying to keep backward compatibility. The current adaptations are enough to keep things running with the completely revised projection metadata storage systems, but more changes will follow, diverging more from legacy.

**Comment by sckott** [comment]
Thanks, I'll have a look. All of those validate tests are a non-issue now as that function is now defunct in the development version and it's tests removed. 

Is there a recommended way to use a particular version of PROJ on macos?

**Comment by rsbivand** [comment]
Thanks!

Sorry, have no OSX access, so can't check. PROJ has some hints here: https://proj4.org/install.html#install, untried. There may also be non-PROJ issues at my end because I was running the github master of **sf** and get different outcomes from Edzer, so instability is a more fitting description than an identified problem. PROJ is going to be unstable for some time, but that's mostly because it wasn't actively maintained for some years.

**Comment by sckott** [comment]
thanks. i'll have a look

**Comment by sckott** [comment]
Closing this. errors were only related to the `validate` fxn, which is now defunct
