### ISSUE TITLE
Dealing with files that are too large

### ISSUE THREAD

**Issue by jsta** [ropensci/geojsonio#153]
Trying to read a very large geojson file results in a cryptic error:

```r
test <- geojsonio::geojson_read(
  "https://opendata.arcgis.com/datasets/d49160d2e5af4123b15d48c2e9c70160_4.geojson")
```

```r
> Error: TRUE
```

Maybe there could be a better message hinting that the file is too large?

**Comment by sckott** [comment]
oof, that's embarrassing, having a look

**Comment by sckott** [comment]
`method="local"` does work at least, but yes, other method should fail better

**Comment by sckott** [comment]
errors better now
