### ISSUE TITLE
Unable to install geojsonio in fedora

### ISSUE THREAD

**Issue by marsupialsoup** [ropensci/geojsonio#171]
When I try to install geojsonio package using 

install.packages('geojsonio', dependencies=TRUE, repos="http://cran.rstudio.com/")

, I even had sudo before I starting R on command line. This is the error I get:

Warning messages:
1: In install.packages("geojsonio", dependencies = TRUE, repos = "http://cran.rstudio.com/") :
  installation of package ‘units’ had non-zero exit status
2: In install.packages("geojsonio", dependencies = TRUE, repos = "http://cran.rstudio.com/") :
  installation of package ‘protolite’ had non-zero exit status
3: In install.packages("geojsonio", dependencies = TRUE, repos = "http://cran.rstudio.com/") :
  installation of package ‘rgeos’ had non-zero exit status
4: In install.packages("geojsonio", dependencies = TRUE, repos = "http://cran.rstudio.com/") :
  installation of package ‘V8’ had non-zero exit status
5: In install.packages("geojsonio", dependencies = TRUE, repos = "http://cran.rstudio.com/") :
  installation of package ‘jqr’ had non-zero exit status
6: In install.packages("geojsonio", dependencies = TRUE, repos = "http://cran.rstudio.com/") :
  installation of package ‘sf’ had non-zero exit status
7: In install.packages("geojsonio", dependencies = TRUE, repos = "http://cran.rstudio.com/") :
  installation of package ‘geojson’ had non-zero exit status
8: In install.packages("geojsonio", dependencies = TRUE, repos = "http://cran.rstudio.com/") :
  installation of package ‘RPostgres’ had non-zero exit status
9: In install.packages("geojsonio", dependencies = TRUE, repos = "http://cran.rstudio.com/") :
  installation of package ‘geojsonio’ had non-zero exit status

**Comment by sckott** [comment]
can you install any packages?

**Comment by marsupialsoup** [comment]
Yes, I can install packages.

**Comment by sckott** [comment]
ok, let me know if it works after installing dependencies. I don't have immediate/easy access to a fedora environment to test

**Comment by marsupialsoup** [comment]
I tested it on a script, I believe it's working.
