### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/geojsonio#178]
Or a new maintainer _team_

If you're interested, please comment in the issue. 
For more info, see

* [our guidance on _Changing package maintainers_](https://devguide.ropensci.org/changing-maintainers.html);
* [our _Package Curation Policy_](https://devguide.ropensci.org/curationpolicy.html).

**Comment by Athene-ai** [comment]
I am  interested

**Comment by mikemahoney218** [comment]
Howdy @maelle ! I'd be open to taking the package on, but I'm not particularly familiar with the geojson format. I'd be able to keep the lights on (and the package on CRAN and so on), but wouldn't be driving any major changes. If anyone more familiar with the format is interested, I'd be more than happy to have them take over instead (or I could assist as needed).

**Comment by maelle** [comment]
Thanks so much @mikemahoney218! Lucky geojsonio :smile_cat: 

How about we leave this open until Friday to see if anyone wants to work with you on this? I'll give you admin access right now though.

**Comment by maelle** [comment]
Do you also need access to https://github.com/ropensci/geojson? I promise I'm not trying to add work on your plate, just tell me if that's needed, otherwise feel free to ignore.

**Comment by mikemahoney218** [comment]
Is Jeroen still interested in geojson? If he isn't, I'd be happy to take it over so the pair stay alive, but if he is then I don't need to replace/join him on it.

**Comment by jeroen** [comment]
@mikemahoney218 I maintain too many packages, would be very happy if you are willing to help with maintaining this one!

**Comment by mikemahoney218** [comment]
Happy to help, then :smile:

**Comment by ateucher** [comment]
Thanks so much @mikemahoney218 for taking this on! I am happy to stay involved and help with issues etc., I'm just really glad you've stepped up to take on the maintenance role!

**Comment by maelle** [comment]
Closing this, thanks again @mikemahoney218 (and @ateucher)!
