### ISSUE TITLE
Maintenance status / help needed?

### ISSUE THREAD

**Issue by maelle** [ropensci/geojsonio#179]
@mikemahoney218 

Do you still intend to become this package's maintainer?

If so do you need any help? For instance an aspect where you'd appreciate some tips, contributions, a PR review? Do you need an invitation to our friendly Slack workspace?

**Comment by maelle** [comment]
Thanks!!

**Comment by mikemahoney218** [comment]
Release tracked in #182 . Package submitted to CRAN at 14:30Z 2022-09-12 :smile:
