### ISSUE TITLE
`usethis::use_testthat(3)` and upgrade to 3e, testthat 3e vignette

### ISSUE THREAD

**Issue by mikemahoney218** [ropensci/geojsonio#183]
The test suite is going to need a good bit of work to get it to work with testthat 3e, but I'd love to get it there. 

This vignette has advice on how to get there:
https://testthat.r-lib.org/articles/third-edition.html

**Comment by mikemahoney218** [comment]
Hey @maelle -- I used `usethis::use_tidy_github_labels()` to update the labels on this repo, which means the ones I just added now have an emoji in the label. Will those still get picked up by rOpenSci's automation for https://ropensci.org/help-wanted/ and similar?

**Comment by steffilazerte** [comment]
Hi @mikemahoney218, I just checked and yes, issues tags with emojis are still caught our script and will be tweeted (probably next week as there is a bit of a delay). I think we might have an issue with the ones displayed online but I'll check with @maelle about that. Thanks!

**Comment by mikemahoney218** [comment]
Awesome, thanks!

**Comment by maelle** [comment]
Indeed we have an issue that is now fixed :sweat_smile: Thanks @mikemahoney218 @steffilazerte for catching it! :pray:

**Comment by maelle** [comment]
See https://ropensci.org/help-wanted/ (you can now hide all our comments if you want to keep this issue thread clean :wink: )

**Comment by czeildi** [comment]
Hi, I am happy to try and give this a go. For context about myself: I have experience with package development and testthat, but I haven't used this package before.

**Comment by mikemahoney218** [comment]
Awesome @czeildi! I'd be happy to look at any PRs you submit. I haven't honestly taken a long look at what needs to happen here -- I know that the test files use a _lot_ of features from the earlier edition, but I think all the changes that are required are testthat-specific and don't have a ton to do with geojsonio itself.
