### ISSUE TITLE
renamed pkg

### ISSUE THREAD

**Issue by sckott** [ropensci/geojsonio#19]
@ateucher as you can see i renamed the pkg to `geojsonio` - i think it makes more sense this way, conveying that it goes to and from geojson, I couldn't find anyword that could stand in for both geojson and topojson

**Comment by ateucher** [comment]
I think that works well. Similar to rjsonio with a geo focus. And topojson is just a special form of geojson, so it seems good to me.

**Comment by sckott** [comment]
okay, cool
