### ISSUE TITLE
install.packages("geojsonio") ERROR

### ISSUE THREAD

**Issue by ved-ux** [ropensci/geojsonio#212]
install.packages("geojsonio")
Installing package into ‘/home/wrf_hydro_fnl/R/x86_64-pc-linux-gnu-library/4.4’
(as ‘lib’ is unspecified)
also installing the dependencies ‘protolite’, ‘geojson’

trying URL 'https://cloud.r-project.org/src/contrib/protolite_2.3.0.tar.gz'
Content type 'application/x-gzip' length 25204 bytes (24 KB)
==================================================
downloaded 24 KB

trying URL 'https://cloud.r-project.org/src/contrib/geojson_0.3.5.tar.gz'
Content type 'application/x-gzip' length 1025678 bytes (1001 KB)
==================================================
downloaded 1001 KB

trying URL 'https://cloud.r-project.org/src/contrib/geojsonio_0.11.3.tar.gz'
Content type 'application/x-gzip' length 791220 bytes (772 KB)
==================================================
downloaded 772 KB

* installing *source* package ‘protolite’ ...
** package ‘protolite’ successfully unpacked and MD5 sums checked
** using staged installation
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-pthread
Using PKG_LIBS=-lprotobuf
Found C++17 compiler: g++ -std=gnu++17 -g -O2 -ffile-prefix-map=/build/r-base-H8urij/r-base-4.4.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2
Using libprotoc 25.3 from /home/wrf_hydro_fnl/WRFHYDRO_STANDALONE/miniconda3/envs/rgee_py/bin/protoc
Warning: protoc version libprotoc 25.3 might not match libproto version 3.12.4.
** libs
using C++ compiler: ‘g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG -pthread -DUSENEWAPI -I'/home/wrf_hydro_fnl/R/x86_64-pc-linux-gnu-library/4.4/Rcpp/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-H8urij/r-base-4.4.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG -pthread -DUSENEWAPI -I'/home/wrf_hydro_fnl/R/x86_64-pc-linux-gnu-library/4.4/Rcpp/include'    -fvisibility=hidden -fpic  -g -O2 -ffile-prefix-map=/build/r-base-H8urij/r-base-4.4.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -c geobuf.cpp -o geobuf.o
In file included from geobuf.cpp:1:
geobuf.pb.h:15:2: error: #error "This file was generated by a newer version of protoc which is"
   15 | #error "This file was generated by a newer version of protoc which is"
      |  ^~~~~
geobuf.pb.h:16:2: error: #error "incompatible with your Protocol Buffer headers. Please update"
   16 | #error "incompatible with your Protocol Buffer headers. Please update"
      |  ^~~~~
geobuf.pb.h:17:2: error: #error "your headers."
   17 | #error "your headers."
      |  ^~~~~
In file included from geobuf.cpp:1:
geobuf.pb.h:29:10: fatal error: google/protobuf/generated_message_tctable_decl.h: No such file or directory
   29 | #include "google/protobuf/generated_message_tctable_decl.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:204: geobuf.o] Error 1
ERROR: compilation failed for package ‘protolite’
* removing ‘/home/wrf_hydro_fnl/R/x86_64-pc-linux-gnu-library/4.4/protolite’
Warning in install.packages :
  installation of package ‘protolite’ had non-zero exit status
ERROR: dependency ‘protolite’ is not available for package ‘geojson’
* removing ‘/home/wrf_hydro_fnl/R/x86_64-pc-linux-gnu-library/4.4/geojson’
Warning in install.packages :
  installation of package ‘geojson’ had non-zero exit status
ERROR: dependency ‘geojson’ is not available for package ‘geojsonio’
* removing ‘/home/wrf_hydro_fnl/R/x86_64-pc-linux-gnu-library/4.4/geojsonio’
Warning in install.packages :
  installation of package ‘geojsonio’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp6U5P18/downloaded_packages’
>

**Comment by mikemahoney218** [comment]
Sorry, reading your logs, this is an issue with `protolite` not installing. This isn't an issue with this package, I don't think.

**Comment by ved-ux** [comment]
@mikemahoney218  thank you
