### ISSUE TITLE
topojson, possibly remove node dependency?

### ISSUE THREAD

**Issue by sckott** [ropensci/geojsonio#22]
GDAL can only read topoJSON via the geoJSON driver, so if we remove the node function, the pkg can't write topojson, but maybe that's okay.  Keep looking around for a non-node way to write topojson

**Comment by ateucher** [comment]
I think for a lot of people it would be very handy to keep it in.  In your experience, will CRAN reject it because of this external dependency? I'm pretty sure rgdal requires gdal to be installed for the package to work (for Linux at least), so not sure how this is different?

**Comment by sckott** [comment]
Okay, so I'm not positive that we couldn't get it through CRAN, but I imagine it might not fly. GDAL is a C or C++ library, which works fine on CRAN.  the npm module topojson is only used for one function https://github.com/ropensci/geojsonio/blob/master/R/topojson_write.r so nota  huge change to this pkg. If we do take out, we could put it in a separate tiny R package just for wrapping the topojson npm module

**Comment by ateucher** [comment]
Ah, I see, that makes sense. I like that idea a lot actually.

**Comment by ateucher** [comment]
Actually, isn't that what this is: https://github.com/joelgombin/toTopoJSON?

**Comment by sckott** [comment]
heh, right, i forgot, that's why his name is in the author list in this pkg. if we take out, we can redirect users to his pkg

**Comment by ateucher** [comment]
:+1:

**Comment by timelyportfolio** [comment]
:+1:

**Comment by sckott** [comment]
see comment https://github.com/ropensci/geojsonio/issues/24#issuecomment-94594884

removing the node dependency for now, will reintroduce ability to write topojson later version
