### ISSUE TITLE
methods for map_gist for each class

### ISSUE THREAD

**Issue by sckott** [ropensci/geojsonio#26]

**Comment by lmullen** [comment]
Would you be interested in using cartographer to do this? It can currently
do GeoJSON polygons; the others could be added. Just a thought, since using
a gist for mapping is a little less reliable than doing it locally.

**Comment by sckott** [comment]
@lmullen good idea - I ended up finishing off the `map_gist()` methods as i was nearly done

But, would be cool to see if we can use `cartographer` here too. What's the appropriate function I should look for?

**Comment by lmullen** [comment]
It's the `geojson_layer()` function, described in the vignette [here](http://lincolnmullen.com/research/cartographer/#geojson). Right now that only works with polygons; I need to think about the best way to implement points and lines.

I'm going to remove the `sp_to_geojson()` function in cartographer and replace it with the geojsonio functions.

**Comment by sckott** [comment]
@lmullen Great, thanks.  Will start this...

**Comment by sckott** [comment]
working on cleaning these up right now, though problem with largish files ropensci/gistr#27

**Comment by sckott** [comment]
think this is done
