### ISSUE TITLE
Use cartographer mapping functions, e.g., `geojson_layer()`

### ISSUE THREAD

**Issue by sckott** [ropensci/geojsonio#28]
from #26

**Comment by sckott** [comment]
@lmullen started an interface to your package, not sure if it makes sense since I just started using it...

see the `map()` function - I wonder if this is a problem though if each of these packages imports the other?

**Comment by lmullen** [comment]
I was thinking you might want to use cartographer for examples and vignettes and so only in the `Suggests` field, but now I see you have bigger plans. I suspect that I won't need to depend on geojsonio but will instead point people to it in examples and vignettes. I'll have to see once I can work on cartographer more. Will including geojsonio in `Suggests` avoid problems?

**Comment by sckott** [comment]
@lmullen hmmm, thinking about this more, of course after I've done it, you are right that it makes more sense with `cartographer` in `Suggests` to show examples - I'll do that - I think we're good if I have `cartographer` in `Suggests` and you have `geojsonio` in `Suggests`

**Comment by lmullen** [comment]
Sounds good.
