### ISSUE TITLE
Failed to install on R 3.1.2

### ISSUE THREAD

**Issue by xinye1** [ropensci/geojsonio#29]
In addition: Warning message:
package ‘cartographer’ is not available (for R version 3.1.2)

OS: Ubuntu 14.04 LTS

Thanks

**Comment by sckott** [comment]
@xinye1 sorry about that, just today added a new pkg import `cartographer` - i updated the readme install instructions - follow this: https://github.com/ropensci/geojsonio#install

**Comment by sckott** [comment]
@xinye1 sorry to flip flop, but i removed cartographer, so that's no longer needed

**Comment by xinye1** [comment]
Nice.
Great package. Thanks!
