### ISSUE TITLE
geojson_json.num returns invalid point

### ISSUE THREAD

**Issue by lmullen** [ropensci/geojsonio#30]
Running this example

```
geojson_json(c(-80, 40))
```

returns

```
{"type":"Point","geometry":{"type":"Point","coordinates":[-80,40]},"properties":{}} 
```

According to GeoJSON lint, that is not valid. One possible option is to return something like this:

```
{"type":"Point","coordinates":[-80,40],"properties":{}} 
```

But even better would be to return a `FeatureCollection` for all GeoJSON objects, so that receiving code could work with them in the same way. For instance,

```
geojson_json(head(us.cities, 2), lat = "lat", lon = "long")
```

returns 

```
{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[-99.74,32.45]},"properties":{"name":"Abilene TX","country.etc":"TX","pop":"113888","capital":"0"}},{"type":"Feature","geometry":{"type":"Point","coordinates":[-81.52,41.08]},"properties":{"name":"Akron OH","country.etc":"OH","pop":"206634","capital":"0"}}]} 
```

I think it would be idea if each method returned a `FeatureCollection`.

**Comment by sckott** [comment]
you're right that that point output is not valid

thinking about the `FeatureCollecting` thing, a `GeometryCollection` could optionally be returned

@ramnathv any opposition to returning everything as a `FeatureCollection`?

**Comment by ramnathv** [comment]
@sckott That should work I think. Do you want to create a separate branch so that we can test it out before rolling it out to the master?

**Comment by sckott** [comment]
Yes, sounds good on a sep branch. Will do that soon

**Comment by sckott** [comment]
@lmullen @ramnathv  what's your feeling on `GeometryCollection` types?  Do you use them?  We could default to `FeatureCollection` as output, but allow user to choose `GeometryCollection`

**Comment by ramnathv** [comment]
I have not used `GeometryCollection` much. Does `github` render these?

I would agree with having `FeatureCollection` as the default and letting the user switch to `GeometryCollection` if desired.

**Comment by sckott** [comment]
Yes, github gists at least renders `GeometryCollection`. https://gist.github.com/sckott/b3901e750381ab9f4f43 is in `GeometryCollection` format, from the example for that type at http://geojsonlint.com/

**Comment by lmullen** [comment]
I haven't used `GeometryCollection` before, but I like your idea of having
`FeatureCollection` as the default and letting users switch to
`GeometryCollection`.

**Comment by sckott** [comment]
@lmullen check it out after installing from featcoll branch  `install_github("ropensci/geojsonio@featcoll")`

**Comment by sckott** [comment]
for now, sp classes can only be output as `FeatureCollection` as we use `rgdal::writeOGR` to make geojson from those classes

**Comment by lmullen** [comment]
@sckott I tested that branch and it looks great.

**Comment by ramnathv** [comment]
@sckott It looks good.

**Comment by sckott** [comment]
great, i'll write a few more tests to make sure I didn't miss anything, then merge in

**Comment by sckott** [comment]
closing, about to merge to master
