### ISSUE TITLE
Guess lat/long columns from data inputs

### ISSUE THREAD

**Issue by sckott** [ropensci/geojsonio#32]
Seems logical to try to guess lat and long columns from data inputs (e.g., data.frame, named list, we should be fine on sp classes), and if not, then fail with message that lat and long columns could not be determined - so please specify...

**Comment by lmullen** [comment]
The `leaflet` package does this nicely with its [`getLatLongColumns()` function](https://github.com/rstudio/leaflet/blob/5c82288d33f5a94b9b9becdcdfb0547f66111817/R/normalize.R#L3).

**Comment by sckott** [comment]
Nice, thanks @lmullen ! i imagine we can repurpose that code?

**Comment by sckott** [comment]
this is done
