### ISSUE TITLE
Method to add together features 

### ISSUE THREAD

**Issue by sckott** [ropensci/geojsonio#36]
E.g., 

```r
geojson_list(<points>) + geojson_list(<polygon>)
```

to make a `FeatureCollection` with both

**Comment by sckott** [comment]
the simple part is done of joining `geo_list` objects together, and joinging `json` objects together, but need to figure out how to add together objects of different types, e.g. `geo_list` + `json`, `geo_list` + `json` + `SpatialPoints`

**Comment by sckott** [comment]
good for `v0.1` - try to figure out remainder of problem for next mliestone

**Comment by hansthompson** [comment]
I really like your package and use it with with leaflet. It would be really awesome to see this new feature. I've been playing around with maybe doing it the slow and dirty way: 
1. converting each json object to a string.
2. removing the featurecollection & features/geometerycollection & geometries headers and ending brace
3. concatenating each feature with a coma 
4. Adding back the headers and ending brace. 

The problem I run into here is that jsonlite::toJSON wants to wrap the whole thing as a single element.  Do you know a way turn the string into a json class without it having to be a list?  

Again, thanks for this package.

**Comment by sckott** [comment]
@hansthompson glad you like it :smile_cat: 

This does exist in the package now, just doesn't combine different classes, only within class. 

> I've been playing around with maybe doing it

What is __it__ here?  What are you trying to combine?  

> The problem I run into here is that `jsonlite::toJSON` wants to wrap the whole thing as a single element. Do you know a way turn the string into a json class without it having to be a list?

be easier to understand if you could give a brief example, plz

**Comment by sckott** [comment]
any thoughts @hansthompson

**Comment by ateucher** [comment]
IMHO, I don't think it's necessary to be able to combine different classes. I don't think it's too much to ask of a user to make the objects that they want to combine of the same class...

**Comment by sckott** [comment]
yeah, prob. right. - if so, we can close then I think

**Comment by ateucher** [comment]
If I were a new user of the package, I doubt it would cross my mind that it *should* be possible.

**Comment by sckott** [comment]
right, closing
