### ISSUE TITLE
Full-package code review, per request

### ISSUE THREAD

**Issue by noamross** [ropensci/geojsonio#45]
## General:

-   This package adheres well to all the packaging guide standards.  

## Tests 

-   Tests all pass
-   Reported coverage is 16%.  This seems low.  Is it because of extensive use of S3 methods?

## README and vingettes:

Errors found:

-  README.Rmd line 119: The `plot()` command yields an error.  There is not a plot method for the type (which is "list").
    -   Shouldn't `geojson_read()` return an object that is also of class `geo_list`

-  README. Rmd line 130: Error:

       Error in match.arg(method, choices = c("web", "local")) : 
         argument "method" is missing, with no default
  
  This appears to be due to an error in `topojson_read()`, which calls `read_json()` without passings `method` and `parse` arguments.
  
-  README.Rmd line 154: Error:

        Error in RCurl::fileUpload(path, contentType = type) : 
          specified file does not exist: https://raw.githubusercontent.com/glynnbird/usstatesgeojson/master/connecticut.geojson.  You must specify a valid file name or provide the contents to send.
          
    I think this is because you are passing a url rather than a file.  to `httr::upload_file()` when uploading the files to Ogre.  You may need to download and then upload for this to work.
    
-   The vingettes are *.Rmd files, but their content is post-knitted markdown.
        
        
## Documentation

-   I think anything that makes use of GDAL needs a prominent link in the documentation to resources for how to intall rgdal/GDAL (Such as [this](http://tlocoh.r-forge.r-project.org/mac_rgeos_rgdal.html) for OSX.)

## Misc

-   I don't yet understand the purpose of `location` objects.  
-   I would expect `map_gist` to have methods for `json` or `geo_list` objects.
    -   Relatedly, should `json` objects also have class `geojson` for various methods reasons?
-   `map_gist()` is great, but I think it would be useful to have a local default plotting method for `json/geojson` or `geo_list` objects.
    These could leverage `sp` methods, or maybe use a leaflet html widget. (Possibly for a future version).
-   is.url() is defined twice - once in `as.location.R` and once in `file_to_geojson.r`
-   Possible other error in the `lint()` examples:

        lint('{"type":"Point","geometry":{"type":"Point","coordinates":[-80,40]},"properties":{}}')
        $message
        [1] "\"coordinates\" property required"
        
        $line
        [1] 1
    
    Doesn't this *have* a `coordinates` property?
-   There are numerous errors in vignettes and examples because the `system.file()` calls use the package name `"togeojson"` rather than `"geojsonio"`.
-   For `file_to_geojson()` I would expect the default behavior be to return the json/list rather than write it to file.  Also, the default location should be the current working directory, not the root directory.

## Meta

-   This review took me about 3.5 hours
-   Reading S3-intensive code is much more cognitively draining and time-consuming than functional code.  Just an FYI for future reviews.
-   I didn't have an easy-to-grab use case to try out this package on, as I did for `rdrop2`.  Working through that use case helped identify bugs and UI improvements. We might try selecting reviewers partially based on whether they have something available to try the package out on.

**Comment by sckott** [comment]
> Reported coverage is 16%. This seems low. Is it because of extensive use of S3 methods?

I just need to write more tests!

**Comment by noamross** [comment]
One quick thing I forgot:

-  \``+`\` not covered in README or vignettes.  It's probably a good idea to have it there.  It's a nice feature and such operators are always a bit challenging to discover in the help.

**Comment by sckott** [comment]
first, thanks a million @noamross for doing this.  To do, AFAIK:

* on the `+` methods - agreed, need to document that, will do
* fill out test suite
* 
* 
* 
* 
*

**Comment by karthik** [comment]
> I didn't have an easy-to-grab use case to try out this package on, as I did for rdrop2. Working through that use case helped identify bugs and UI improvements. We might try selecting reviewers partially based on whether they have something available to try the package out on.

That's an excellent suggestion @noamross! Will have to keep that in mind.

**Comment by sckott** [comment]
discussion of more general reviewing topics moved to , lat1 = bnds$lat1

**Comment by sckott** [comment]
i've addressed everything here, a few issues opened up to deal with later
