### ISSUE TITLE
'Invalid cross-device link' - file renaming fails

### ISSUE THREAD

**Issue by caraka** [ropensci/geojsonio#50]
*file.rename*, as used in zzz.r, can fail across file systems. In my use case it fails when geojson_write() attempts to rename the output between an unencrypted /tmp/file where it is created and my encrypted /home folder, the designated output location.

The fix, according to google, is straightforward [TM that!]. Replace *file.rename* with *file.copy*. I have done so within my branch, and it has sorted my issue. 

*I have done no further testing.*

Feel free to ignore my pull request if you think this will adversely effect other things.
Thanks for your work!

**Comment by sckott** [comment]
hi @caraka - 

I haven't seen this issue, so I'm glad you're bringing this up.  

That seems to work fine, so I'll merge the PR
