### ISSUE TITLE
geojsonio fails to load under Windows XP, plus proposed fix

### ISSUE THREAD

**Issue by justa9** [ropensci/geojsonio#55]
Running "library(geojsonio" returns an error:

"The procedure entry point _localtime32_s could not be located in the dynamic link library msvcrt.dll".

jsonlite had a similar problem but was resolved thus:
https://github.com/jeroenooms/jsonlite/blob/master/src/yajl/yajl_tree.c#L28-L30

**Comment by sckott** [comment]
You were able to install the package though?  your code above has `library(geojsonio` without the closing parentheses. Is that a typo?  `jsonlite` is an import in this package, so I imagine if a fix was put in there, it would be helpful for you (as long as you have that version of `jsonlite`)  What version of `jsonlite` do you have?

**Comment by justa9** [comment]
Yes, deeply sorry for the typo.  jsonlite loads and works correctly.

The (binary) package of geojsonio is succesfully installed. However, when I try to load it, I get the same error. I did try to compile from source (last night, as I caught up an announcement at social media), but the same error was reported.

Just to be clear: The error message I posted previously is a pop-up window.

The error returned in the console is this:
```
Error in inDL(x, as.logical(local), as.logical(now), ...) :
  unable to load shared object 'C:/Program Files/R/library/V8/libs/i386/V8.dll':
  LoadLibrary failure:  The specified procedure could not be found.

Error: package or namespace load failed for 'geojsonio'
```

**Comment by sckott** [comment]
No worries about typo. Looks like a V8 problem. an you install and load `V8` package successfully?

**Comment by justa9** [comment]
I edited the comment instead of posting again.

V8 is the culprit (and does not load)

**Comment by sckott** [comment]
@justa9 okay, thx

@jeroenooms any thoughts on windows XP and `V8`

**Comment by sckott** [comment]
sorry @justa9 - still trying to figure this out, makes it harder since I can't seem to find a windows xp machine to test things on

**Comment by jeroenooms** [comment]
I'm sorry I don't have a windows XP machine either, it might be very hard to debug this. Given that the system is officially deprecated, I am not sure if it's really worth it getting to the bottom of this.

**Comment by sckott** [comment]
Okay, thanks @jeroenooms

**Comment by sckott** [comment]
@justa9 one solution is to put `V8` in `Suggests`, and then its not required for loading the package, V8 is not needed in most of this package right now, but I have plans to use it more widely in this package, so it wouldn't make sense to do that soon

see #57

**Comment by sckott** [comment]
@justa9 is there any chance you can upgrade your windows OS soon?

**Comment by jeroenooms** [comment]
@justa9 Is it just V8 or are you also having issues with other `Rcpp` packages? It's really difficult to debug this. Why are you running such an old system? If you don't want to pay for a new one, have you considered switching to linux?

**Comment by justa9** [comment]
Apologies for the delay in answers

@sckott I cannot afford either a new update or a transition to linux-based OS, however I am willing to try out proposed fixes.

@jeroenooms I have not come up across any other kind of problem regarding Rcpp packages, although I am not sure whether I have used that many of them.  Still I am willing to try out proposed fixes.

**Comment by sckott** [comment]
@justa9 sorry about this - but I don't know what to offer other than i'd suggest googling around to see if you can get V8 installed on windows xp. sorry for not being more helpful!

**Comment by benmarwick** [comment]
One possible workaround here might be to use RStudio in a Docker container via the [Rocker project](https://github.com/rocker-org/rocker/wiki/Using-the-RStudio-image). Then you should be able to do anything that Linux can do. The key requirement is 64-bit Windows. 

That will give you a Linux OS inside the regular Windows OS. Not 100% sure about XP. but works great with Windows 7.

**Comment by sckott** [comment]
thanks for the comment @benmarwick - trying to see if i can figure out how to get v8 on xp

**Comment by sckott** [comment]
@justa9 Is Rocker something you can try?  See comment by @benmarwick above

**Comment by jeroenooms** [comment]
@sckott how did you get your hands on an xp box?

**Comment by sckott** [comment]
@jeroenooms here http://dev.modern.ie/tools/vms/#downloads

**Comment by jeroenooms** [comment]
ah cool. I thought they were no longer offering those because xp is deprecated. But I guess they still work.

**Comment by sckott** [comment]
yeah, i don't know why they are pitched as IE testing boxes, but at least I could install things on there, R, Rstudio, etc.

**Comment by justa9** [comment]
@skcott Since Rocker requires 64-bit, I am out of luck :-(

**Comment by jeroenooms** [comment]
@justa9 can you try to install the development version of v8 from github?

**Comment by sckott** [comment]
@jeroenooms but didn't you roll back that change https://github.com/jeroenooms/V8/issues/12#issuecomment-106123210

**Comment by jeroenooms** [comment]
Later I added a hack: https://github.com/jeroenooms/V8/blob/master/src/Makevars.win#L16-L21

**Comment by justa9** [comment]
I did and it works!

**Comment by justa9** [comment]
@jeroenooms I just did and it works! Thanks a lot guys! Now the CRAN version of geojsonio loads and works as expected.

**Comment by jeroenooms** [comment]
OK i'm glad it works. By the way maybe you can get the free update to windows 10 ;)
