### ISSUE TITLE
Small bug

### ISSUE THREAD

**Issue by karthik** [ropensci/geojsonio#56]
When using `geojson_write` to turn a df into geojson (which is awesome btw), I see that some of the field names get changed. 
e.g.
`marker-size` → `marker.size`
`marker-color` →  `marker.color`

Both of these changes break standard Mapbox fields and I have to manually fix these later.

[full example](https://github.com/karthik/mapbox-test/blob/b471e29e378621926d6e45be6dd6f0e199c8c31b/code.R#L34-L37) (This is now an old commit, see below for current version)

**Comment by karthik** [comment]
For the moment I've fixed this by replacing with `toGeoJSON` from `leafletR` which does this step correctly. 

Line: https://github.com/karthik/mapbox-test/blob/master/code.R#L43

**Comment by sckott** [comment]
thanks for this, i'll look into it

**Comment by sckott** [comment]
okay does that work now after reinstall @karthik

**Comment by karthik** [comment]
Yep, all fixed up. Thanks @sckott!

**Comment by karthik** [comment]
Sorry to add one more thing. It also butchers urls.

```
{ "type": "Feature", "id": 117, "properties": { "title": "Gavia immer", "description": "Collected on NA", "marker-color": "#9E0142", "url": "https:\/\/ecoengine.berkeley.edu\/api\/observations\/CalPhotos%3A8235%2B3181%2B2553%2B0029%3A1\/", "latitude": 36.600279999999998, "longitude": -121.89361, "marker-size": "small" }, "geometry": { "type": "Point", "coordinates": [ -121.89361, 36.60028 ] } },
```

That's also something that needs to be fixed.

**Comment by sckott** [comment]
it's a problem in GDAL/rgdal escaping the string, seeing how to fix

**Comment by sckott** [comment]
no solution yet - still poking around SO and GDAL to see if some way to avoid URL escaping 

FWIW, if I write geojson then read the file back in it parses fine

**Comment by sckott** [comment]
@karthik did you see my last comment?  thoughts?

**Comment by karthik** [comment]
I did, feels ok to leave it for now. I'lll also explore other sources that might help with url escaping. One might not read this file back using geojsonio and with some third party js script, which is where the problem lies.

**Comment by sckott** [comment]
Right, i'll open a new issue just for this escaping thing  - to deal with when solution found
