### ISSUE TITLE
geojson_read - optionally give back sp class

### ISSUE THREAD

**Issue by sckott** [ropensci/geojsonio#60]
with logical parameter

**Comment by Robinlovelace** [comment]
This will be very useful.
In case it helps, a solution from raw json is provided here: https://stackoverflow.com/questions/29066198/how-to-load-part-of-a-multifeature-geojson-file-in-r
I'm happy to test this feature.

**Comment by sckott** [comment]
cool, will do soon

**Comment by sckott** [comment]
@Robinlovelace I added giving back spatial classes as an option in `geojson_read()` - still doesn't work for featurecollection's. I'm wondering if a solution for that will be complicated b/c you can have many different things inside a featurecollection. In addition, we'd need to consider geometrycollection's. I wouldn't want to make system calls in a package, too messy. But we could parse the geojson to a list, then convert each feature, then combine back together into a spatial class.

**Comment by Robinlovelace** [comment]
Sounds good. I think what is needed is a way to identify the 'core' spatial objects (primarily SpatialLines, Points and Polygons and DataFrames) and then extract them in a generic way. A way to split these features in list form (Filter???) means we're half-way there. Then it's just a question of creating a function for converting a list to a Spatial* object, list2sp(), for example... Any way I can help let me know, although I find the complex lists that represent spatial objects baffling.

**Comment by sckott** [comment]
Okay, i'll get started on it and ping you for feedback, etc.

**Comment by Robinlovelace** [comment]
@sckott confirmed: your `what="sp"` argument works perfectly.

Those spatial classes are really important for a whole host of GIS/Scientific packages so many thanks for working on this.

**Comment by sckott** [comment]
@Robinlovelace cool!

**Comment by sckott** [comment]
looks done
