### ISSUE TITLE
Update rgdal dependency due to fixed bug in rgdal::writeOGR

### ISSUE THREAD

**Issue by ateucher** [ropensci/geojsonio#69]
There was a bug in `rgdal::writeOGR` that resulted in multipolygon objects not being written to geojson correctly (and other spatial types that use the Simple Features specification - basically everything other than ESRI). You can follow the thread here: https://stat.ethz.ch/pipermail/r-sig-geo/2015-October/023609.html

Roger Bivand was a rock star and implemented a fix impressively quickly, which is hitting CRAN now in version 1.1-1 (source is up to date, binaries are trickling in).  I'd recommend making rgdal 1.1-1 a minimum requirement.

**Comment by sckott** [comment]
Thanks @ateucher 

Good idea, agree to require that version

**Comment by ateucher** [comment]
:+1:

**Comment by sckott** [comment]
Blargh. Fixed. But need to install more recent version on travis.  Using binary Linux install, but installing v0.8 ish

**Comment by sckott** [comment]
@ateucher know how to get `rgdal v.1-1-1` on travis?  We're using the easy `r_binary_packages: - rgdal` with `language: r`, but looks like where that comes from doesn't have this version http://ppa.launchpad.net/marutter/c2d4u/ubuntu/pool/main/r/rgdal/

**Comment by ateucher** [comment]
Argh!

You might want to check out my travis.yml for rmapshaper for installing
those deps: https://github.com/ateucher/rmapshaper/blob/test-v8/.travis.yml.
It took a lot of googling and head bashing to get it to work.  A caveat
though - I have some tests that fail on Travis that pass on my work Windows
machine, as well as my Mac and Linux laptops at home, so I think it may
have something to do with that gdal/rgdal setup...

**Comment by sckott** [comment]
nice, thanks @ateucher 

Gavin said that the ppa should be updated in a few days. so I'll hold out for that as it's just one line of code :)

**Comment by ateucher** [comment]
Good call. I may have to try that too...

**Comment by sckott** [comment]
opening back up until travis is building okay with new version

**Comment by sckott** [comment]
@ateucher  Hmm, looks like CRAN still does not have mac binaries for `rgdal v1.1-1`, despite that version hitting CRAN two weeks ago. 

I imagine if we require `rgdal v1.1-1`, people on mac will be sad. 

Thoughts?

**Comment by ateucher** [comment]
Oh that's a bugger. How long does it usually take?

**Comment by sckott** [comment]
No idea. Sometimes it can definitely take a while. Whenever I email CRAN maintainers about this kind of thing I never get a response, but maybe could work

**Comment by ateucher** [comment]
Yeah, it's a tricky spot for sure. You're ready to submit to CRAN eh?  What about waiting a few more days?  It would be a pity to not include the dependency and then have the rgdal binary go up right after you submit.  Personally I think it's a critical enough bugfix that the dependency is pretty important...

**Comment by sckott** [comment]
Was hoping to submit soon to get this new rgdal version requirement to users, but would prefer if osx binaries were up. Let's wait a bit.

**Comment by ateucher** [comment]
I wonder if it's worth a poke about those OSX binaries? Or submit this version to CRAN, then ask about the rgdal binaries? It's been over two weeks since 1.1-1 went up on CRAN...

PS. Congrats about the rOpensci funding! Huge news!

**Comment by sckott** [comment]
I'll email about before we submit.

Thanks!

**Comment by ateucher** [comment]
:+1:

**Comment by sckott** [comment]
@ateucher looks like we haven't had up to date osx binaries for many versions of `rgdal` https://cran.rstudio.com/src/contrib/Archive/rgdal/ sadface, ill figure out who best to email

**Comment by ateucher** [comment]
Ahhh, strange eh? According to Roger it's Simon Urbanek: https://mailman.stat.ethz.ch/pipermail/r-sig-geo/2015-November/023660.html

**Comment by ateucher** [comment]
Continuing from [here]()

> i worry about osx users though. if we require rgdal > X version they have to install from source, and I don't know if that will end up well or not

It's true... though if they use `rgdal` older than v1.1-1 and try to convert `SpatialPolygons`/`SpatialPolygonsDataFrame` with multipart geometries to geojson, it won't work properly.

What if we didn't require a version, but somewhere in the NEWS/README/DESCRIPTION say that rgdal v1.1-1 or greater is recommended?

**Comment by sckott** [comment]
Yeah, that's probably best to just put in documentation for now, and maybe a `message()` (though maybe that's too annoying

**Comment by ateucher** [comment]
What about in a `packageStartupMessage`?

**Comment by sckott** [comment]
i usually don't use them, but this seems like a good use case

**Comment by sckott** [comment]
sorted for now, using a startup message of the form:

> We recommend using rgdal v1.1-1 or greater, but we don't require it
rgdal::writeOGR in previous versions didn't write
multipolygon objects to geojson correctly.
See https://stat.ethz.ch/pipermail/r-sig-geo/2015-October/023609.html

**Comment by sckott** [comment]
going to push to cran soon
