### ISSUE TITLE
Function to convert geojson to Spatial object?

### ISSUE THREAD

**Issue by ateucher** [ropensci/geojsonio#71]
What do you think about providing a function to convert a geojson object (`geo_list` or `json`) to a Spatial object? I think it would just be a relatively thin wrapper around `readOGR()`?

**Comment by sckott** [comment]
hmmm, sounds easy, will think a bit

**Comment by sckott** [comment]
This?

```r
#' geojson to sp classes
#' 
#' @examples 
#' # geo_list ------------------
#' ## From a numeric vector of length 2 to a point
#' vec <- c(-99.74,32.45)
#' geojson_list(vec) %>% sp_geojson
#'
#' ## Lists
#' ## From a list
#' mylist <- list(list(latitude=30, longitude=120, marker="red"),
#'                list(latitude=30, longitude=130, marker="blue"))
#' geojson_list(mylist) %>% sp_geojson
#' geojson_list(mylist) %>% sp_geojson %>% plot
#'
#' ## From a list of numeric vectors to a polygon
#' vecs <- list(c(100.0,0.0), c(101.0,0.0), c(101.0,1.0), c(100.0,1.0), c(100.0,0.0))
#' geojson_list(vecs, geometry="polygon") %>% sp_geojson
#' geojson_list(vecs, geometry="polygon") %>% sp_geojson %>% plot
#' 
#' # json ------------------
#' ## from point
#' geojson_json(c(-99.74,32.45)) %>% sp_geojson
#' geojson_json(c(-99.74,32.45)) %>% sp_geojson %>% plot
#' 
#' # from featurecollectino of points
#' geojson_json(us_cities[1:2,], lat='lat', lon='long') %>% sp_geojson
#' geojson_json(us_cities[1:2,], lat='lat', lon='long') %>% sp_geojson %>% plot
sp_geojson <- function(x, ...) {
  UseMethod("sp_geojson")
}

#' @export
sp_geojson.geo_list <- function(x, ...) {
  rgdal::readOGR(as.json(x), layer = "OGRGeoJSON")
}

#' @export
sp_geojson.json <- function(x, ...) {
  rgdal::readOGR(x, layer = "OGRGeoJSON")
}
```

**Comment by ateucher** [comment]
I think so. Will you pass `...` to `readOGR`?  I think I would make `disambiguateFIDs = TRUE`. I have run into cases with geojson where there isn't a  unique id field so `readOGR` choked without that parameter.

It may be that the wrapper is so thin and there may be enough cases where one will have to pass other arguments to `readOGR` that it's not worth it.  What do you think?

**Comment by ateucher** [comment]
```r
#' geojson to sp classes
#' 
#' @examples 
#' # geo_list ------------------
#' ## From a numeric vector of length 2 to a point
#' vec <- c(-99.74,32.45)
#' geojson_list(vec) %>% sp_geojson
#'
#' ## Lists
#' ## From a list
#' mylist <- list(list(latitude=30, longitude=120, marker="red"),
#'                list(latitude=30, longitude=130, marker="blue"))
#' geojson_list(mylist) %>% sp_geojson
#' geojson_list(mylist) %>% sp_geojson %>% plot
#'
#' ## From a list of numeric vectors to a polygon
#' vecs <- list(c(100.0,0.0), c(101.0,0.0), c(101.0,1.0), c(100.0,1.0), c(100.0,0.0))
#' geojson_list(vecs, geometry="polygon") %>% sp_geojson
#' geojson_list(vecs, geometry="polygon") %>% sp_geojson %>% plot
#' 
#' # json ------------------
#' ## from point
#' geojson_json(c(-99.74,32.45)) %>% sp_geojson
#' geojson_json(c(-99.74,32.45)) %>% sp_geojson %>% plot
#' 
#' # from featurecollectino of points
#' geojson_json(us_cities[1:2,], lat='lat', lon='long') %>% sp_geojson
#' geojson_json(us_cities[1:2,], lat='lat', lon='long') %>% sp_geojson %>% plot
sp_geojson <- function(x, disambiguateFIDs = TRUE, ...) {
  UseMethod("sp_geojson")
}
#' @export
sp_geojson.geo_list <- function(x, disambiguateFIDs = TRUE, ...) {
  rgdal::readOGR(as.json(x), layer = "OGRGeoJSON", disambiguateFIDs = disambiguateFIDs, ...)
}

#' @export
sp_geojson.json <- function(x, disambiguateFIDs = TRUE, ...) {
  rgdal::readOGR(x, layer = "OGRGeoJSON", disambiguateFIDs = disambiguateFIDs, ...)
}
```

**Comment by sckott** [comment]
yeah, pass on `...` to `readOGR`

`disambiguateFIDs` sounds good

Now that I think about it, maybe it makes more sense to name the fxn `geojson_sp()` as the output is an `sp` class, consistent with `geojson_list` outputting a list, and `geojson_json` outputting json. ?

> It may be that the wrapper is so thin and there may be enough cases where one will have to pass other arguments to readOGR that it's not worth it.

I think it's probably worth it. There's probably some subset of people that don't want to have to worry about the details, and just want to get an sp object

**Comment by ateucher** [comment]
Looks good to me! I agree about the naming - `geojson_sp` makes sense.

**Comment by sckott** [comment]
:+1:

**Comment by sckott** [comment]
@ateucher pushed up the new function. added some tests as well. anything we should change about it?

**Comment by ateucher** [comment]
I think it looks great! I also really like the addition of the `geo_json` class.  I think that will make it safer in a lot of situations.

I also find I use the `p4s` argument in `readOGR` a fair bit due to the inconsitency with reading/writing CRSs. I don't think we need to expose it explicitly in `geojson_sp`, but maybe worth mentioning it in the docs?

I'll suggest some wording...

**Comment by sckott** [comment]
Thanks for the PR

Yeah.  Made sense to change that class.  Hopefully will lead to less problems

**Comment by ateucher** [comment]
:+1:
