### ISSUE TITLE
Bug in spdftogeolist internal fxn

### ISSUE THREAD

**Issue by sckott** [ropensci/geojsonio#76]
not parsing some data correctly

**Comment by ateucher** [comment]
@sckott Do you have a readily-available example?

**Comment by sckott** [comment]
can get some

**Comment by ateucher** [comment]
If you're already on it, it's not critical... mostly just curious as I
don't know if I'll have time to help in the next few days anyway...

**Comment by sckott** [comment]
`spdftogeolist()` is only used in `as.json()` - and so that fxn is affected, but only for the methods for `geojson` and `character` (`as.json.geojson`, `as.json.character`)
