### ISSUE TITLE
pull out linters into new pkg

### ISSUE THREAD

**Issue by sckott** [ropensci/geojsonio#80]
modularize all the things

**Comment by ateucher** [comment]
Hey @sckott, I met @richfitz at UBC yesterday, and we chatted briefly about his very cool [jsonvalidate](https://github.com/ropenscilabs/jsonvalidate) package. I also found what looks to be a [complete geojson schema](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/geojson.json) here: <https://github.com/SchemaStore/schemastore>.

What do you think about using that for validating geojson? It's a lot faster than the current `geojsonio::lint` function, especially if you create a validator using `jsonvalidate::json_validator`:

``` r
# devtools::install_github("ropenscilabs/jsonvalidate")

suppressPackageStartupMessages(library(geojsonio))
library(jsonvalidate)
library(microbenchmark)

geojson_schema <- readLines("https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/geojson.json")

california <- as.json(geojson_read(system.file("examples", "california.geojson", package = "geojsonio")))

geojson_validate <- json_validator(geojson_schema)

microbenchmark(lint(california), json_validate(california, geojson_schema), geojson_validate(california))
```

    ## Unit: milliseconds
    ##                                       expr        min         lq
    ##                           lint(california) 128.394344 132.534349
    ##  json_validate(california, geojson_schema)  50.255769  52.186413
    ##               geojson_validate(california)   3.808048   3.965848
    ##        mean     median         uq       max neval cld
    ##  144.736614 135.874288 161.903107 204.71373   100   c
    ##   60.676324  56.879840  62.222748 114.60032   100  b 
    ##    4.478198   4.042823   4.167107  14.87137   100 a

The [schemastore repo](https://github.com/SchemaStore/schemastore) is under the Apache 2.0 license, so we could include the schema right in the package...

**Comment by ateucher** [comment]
We'd probably want to test that schema quite a bit more though...

**Comment by sckott** [comment]
at https://github.com/ropenscilabs/geojsonlint

**Comment by sckott** [comment]
@ateucher good idea, wonder why geojsonhint is so slow, wonder if there's a accuracy/speed tradeoff  - want to incorporate into the new pkg

**Comment by ateucher** [comment]
is-my-json-valid purports to be the [fastest json validator](https://github.com/mafintosh/is-my-json-valid#performance)...

Yep, I'll work on it!

**Comment by sckott** [comment]
closing, new pkg started, will open a new issue to use the new pkg once on CRAN
