### ISSUE TITLE
geojson_write does not overwrite existing files but says it does

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/geojsonio#81]
I was surprised to see that when updating the dataset for my work that nothing changed in the git diff after using `geojson_write()` to push new data for a project, despite being told the function succeeded.

Further investigation suggests this is bug with the function. Reproducible example:

```
geojson_write(us_cities[1:2,], lat='lat', lon='long', file = "test.geojson")
orig = readLines("test.geojson")
geojson_write(us_cities[2:3,], lat='lat', lon='long', file = "test.geojson")
new = readLines("test.geojson")
identical(orig, new)
```

One would expect `FALSE`, as the function said the new data was written:

```
Success! File is at test.geojson
```

However to my surprise I found it to be `TRUE`. Please try to reproduce on the latest version.

This shows that when the file name is changed it works:

```
> geojson_write(us_cities[2:3,], lat='lat', lon='long', file = "test2.geojson")
Success! File is at test2.geojson
<geojson>
  Path:       test2.geojson
  From class: data.frame
> new2 = readLines("test2.geojson")
> identical(orig, new2)
[1] FALSE
```

Suggest perhaps an `overwrite = TRUE` argument is needed to solve this...

**Comment by sckott** [comment]
Thanks for the report!  will fix

**Comment by sckott** [comment]
I imagine `overwrite = TRUE` as the default is best - given that I'd assume that if I wrote a 2nd object to the same file name that it would replace it

**Comment by Robinlovelace** [comment]
Agreed, especially if it reports `Success!`

**Comment by sckott** [comment]
@Robinlovelace okay, reinstall `devtools::install_github("ropensci/geojsonio")` and try again, new param `overwrite`

**Comment by sckott** [comment]
let me know if you think you like this behavior: when the file is present, and `overwrite=FALSE`, there's a stop message, but any other combo and proceeds as before

**Comment by Robinlovelace** [comment]
That works now, thanks for the fast fix. Suggest getting this one onto CRAN soon as others could be making the same mistake I did. Agile!

**Comment by sckott** [comment]
great, pretty soon, yes
