### ISSUE TITLE
Deprecate linting functions - and use geojsonlint

### ISSUE THREAD

**Issue by sckott** [ropensci/geojsonio#82]
from #80

**Comment by sckott** [comment]
not quite sorted yet...

**Comment by sckott** [comment]
more changes:

* deprecate `validate()` - tell users to use `lint()`
* `lint()` changes:
    * add parameter `method` to choose one of `geojsonlint::geojson_hint`, `geojsonlint::geojson_lint`, or `geojsonlint::geojson_validate`
    * add `verbose` and `error` params

**Comment by sckott** [comment]
Actually, maybe we should just remove all linting functions (`lint()` and `validate()`) in this package, and tell users to go use  `geojsonlint` - Does that sound good @ateucher ?

If so, we can deprecate both those functions now for this next version `v0.2` https://github.com/ropensci/geojsonio/milestones/v0.2 that I'm hoping to push to cran soon, then make them defunct in the following version.

**Comment by ateucher** [comment]
I think that makes sense. +1

**Comment by sckott** [comment]
Okay, will do
