### ISSUE TITLE
'file_to_geojson' - error when reading from 'special' url

### ISSUE THREAD

**Issue by patperu** [ropensci/geojsonio#83]
Hello @sckott,

I want to convert a shpfile (as zip) to geojson, the input comes from an url.

```{r}
library('geojsonio')
url <- 'http://odn.comune.prato.it/geonetwork/srv/en/resources.get?uuid=f7077224-bf61-4b1e-904b-f3668ef80859&fname=WIFI_COPERTURA.zip&access=private'
out <- file_to_geojson(input=url, method='web', output='wifi-free-web')
## Success! File is at wifi-free-web.geojson
```

But the generated geojson is not valid, it contains this:

```{r}
readLines("wifi-free-web.geojson", n = -1)
## [1] "{\"errors\":[\"invalid distance too far back\"]}"
```

If I use the same file from a different location, everything looks good (well, not really.. but this will be another issue :wink: )

```{r}
url <- 'http://www.covimo.de/wifi/WIFI_COPERTURA.zip'
out <- file_to_geojson(input=url, method='web', output='wifi-free-web-covimo')
substring(readLines("wifi-free-web-covimo.geojson", n = -1), 1, 150)
#[1] "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"properties\":{\"ID\":7},\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[1668528.9793110648,48612"
```

Ciao
Patrick

**Comment by sckott** [comment]
thanks for the issue @patperu - will have a look

**Comment by sckott** [comment]
what version of `geojsonio` do you have

**Comment by patperu** [comment]
Hello @sckott ,
upps, sorry for missing this info.. 
I'm using geojsonio 0.1.8 (ropensci/geojsonio@708f11e)

BTW, I'm going to open another issue (not connected) in a few minutes, so maybe you want to wait.

**Comment by sckott** [comment]
I've not seen the error `invalid distance too far back` - it doesn't look like an error that happens in `geojsonio`

**Comment by patperu** [comment]
Hmm, ok. 
I  found this
- https://github.com/ymnk/jzlib/issues/14
- http://stackoverflow.com/questions/34396566/error-invalid-distance-too-far-back-when-inflate-html-gzip-content
Seems more a zlib issue. Will try it tomorrow on another (windows) machine. 

Ciao
Patrick

**Comment by sckott** [comment]
yeah, that makes sense that it's a problem with reading from the url

Have you tried using `method="local"` ?

**Comment by patperu** [comment]
Hello @sckott ,
couldn't try it on another windows machine, hopefully tomorrow. With Ubuntu it works without a problem for both methods `local` and `web`.
Ciao
Patrick

**Comment by sckott** [comment]
thanks for update

**Comment by sckott** [comment]
@patperu did you get this sorted out?

**Comment by patperu** [comment]
Hello @sckott 
the reason is `download_file` in `handle_remote` - under windows (two different machines)
```r
url <- 'http://odn.comune.prato.it/geonetwork/srv/en/resources.get?uuid=f7077224-bf61-4b1e-904b-f3668ef80859&fname=WIFI_COPERTURA.zip&access=private'
download.file(url, destfile = "WIFI_COPERTURA.zip")
``` 
`WIFI_COPERTURA.zip` is not a valid zip-file.

But this works:
```r
library('httr')
library('geojsonio')
t_ok   <- content(GET('http://www.covimo.de/wifi/WIFI_COPERTURA.zip'))
t_fail <- content(GET('http://odn.comune.prato.it/geonetwork/srv/en/resources.get?uuid=f7077224-bf61-4b1e-904b-f3668ef80859&fname=WIFI_COPERTURA.zip&access=private'))
identical(t_ok, t_fail)
#[1] TRUE

outfile <- file("WIFI_COPERTURA.zip", "wb")
     writeBin(t_fail, outfile, raw())
close(outfile)



file_to_geojson("WIFI_COPERTURA.zip", method='web', output='WIFI_COPERTURA')
substring(readLines("WIFI_COPERTURA.geojson"), 1, 75)
# [1] "{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"properties\":{\"ID"
```

**Comment by sckott** [comment]
thanks @patperu I'll have a look

**Comment by sckott** [comment]
@patperu try reinstalling `devtools::install_github("ropensci/geojsonio")`

i tested on my windows VM, try it on your windows machine. I think it should work now. let me know

**Comment by patperu** [comment]
Hi @sckott, looks good! I'm using the latest version (4d0f8cc17b) and it works now.
Thank you! 
Patrick :wave:

**Comment by sckott** [comment]
great, glad it works
