### ISSUE TITLE
Read file with 'geojson_read' - error when plotting

### ISSUE THREAD

**Issue by patperu** [ropensci/geojsonio#84]
Hello @sckott 

I try to plot a map, which I imported via `geojson_read` but I receive an error

```{R}
library('geojsonio') # 0.1.8  (ropensci/geojsonio@708f11e)
library('rgdal')     # 1.1-8

url <- 'http://www.covimo.de/wifi/WIFI_COPERTURA.zip'
out <- file_to_geojson(input=url, method='web', output='wifi-free-web-covimo')
wifi <- geojson_read("wifi-free-web-covimo.geojson")

plot(wifi)
# Error in xy.coords(x, y, xlabel, ylabel, log) : 
#   'x' is a list, but does not have components 'x' and 'y'
```

Using the same geojson with `readOGR` it works

```{R}
map2 <- readOGR("wifi-free-web-covimo.geojson", "OGRGeoJSON")
# ok
plot(map2)
```

Thank you very much for all your great work!
Patrick

**Comment by sckott** [comment]
easy peasy

```r
plot(geojson_read("wifi-free-web-covimo.geojson", what = "sp"))
```

![screen shot 2016-04-14 at 10 14 30 am](https://cloud.githubusercontent.com/assets/577668/14536938/b9d0fa6c-0229-11e6-8984-e8a05e18fdf3.png)

**Comment by sckott** [comment]
the default that comes back is a list, so say you want an sp object (that is, a spatial object)

**Comment by patperu** [comment]
Arrg! Rock solid software :rocket: - I should read the helpfiles!

Thanks a lot!
Patrick
