### ISSUE TITLE
brief output for geojson_json 

### ISSUE THREAD

**Issue by sckott** [ropensci/geojsonio#86]
These functions can return very verbose output. 

Thinking about print methods for each that only give very brief output and calculate some summary information to print as well if possible

**Comment by ateucher** [comment]
Great idea! Include: geometry type, crs, bounding box, number of features, field names (and types)... `head` of data?

**Comment by sckott** [comment]
cool . - I think it makes sense to follow what we'll do for the geojson package https://github.com/ropenscilabs/geojson

**Comment by ateucher** [comment]
Oh nice. So what's the relationship there... is the intent to have this (and all other geojson-focussed packages such as `lawn`) depend on `geojson` package for the classes?

**Comment by sckott** [comment]
`geojson` is like `sp`, with classes for all geojson data types, and some very minimal manipulation tools __sans__ depending on `sp`/`rgdal`/etc. 

and https://github.com/ropenscilabs/geoops for trying to have equiv. to `rgdal`/`rgeos`  (a subset of their operations at least), but only using `jqr` if possible

For `geojsonio` though, i just meant follow what we'll use for `geojson` for a print method for defining classes - though this isn't super important, anyway, will get something drafter and ask for your feedback

**Comment by ateucher** [comment]
Ok, that's what I figured...

**Comment by sckott** [comment]
moving this to next milestone, I think we should send what we have so far for `v0.3` https://github.com/ropensci/geojsonio/milestone/3?closed=1

**Comment by sckott** [comment]
@ateucher can you take a look and tell me what you think?  install  `devtools::install_github("ropensci/geojsonio@json-brief")`

**Comment by sckott** [comment]
changes only in `geojson_json` function - just run examples to see after installation

**Comment by fmichonneau** [comment]
+1 for this. I too often crash my R session by trying to print a 10Mb geo_json object :neutral_face:

**Comment by sckott** [comment]
thanks @fmichonneau motivation to get this done sooner

**Comment by sckott** [comment]
Since it'd be best to handoff the heavy lifting to `geojson`, i think we move forward with brief output for json as a string for now and then do brief output for lists once lists are supported in `geojson` - see https://github.com/ropensci/geojson/issues/18
