### ISSUE TITLE
Number of digits

### ISSUE THREAD

**Issue by ateucher** [ropensci/geojsonio#96]
Currently [`to_json`](https://github.com/ropensci/geojsonio/blob/master/R/zzz.r#L4) includes 22 digits. The [GDAL default](https://github.com/ropensci/geojsonio/blob/master/R/zzz.r#L4) is 7. 

22 seems excessive to me. Should we reduce it? should it be controllable by an additional argument?

`write_geojson` methods for `sp` objects currently allows specification of digits via the `precision` argument in  (default `NULL`)

**Comment by sckott** [comment]
Agree to reduce it - I looked over the new GeoJSON spec, and it seems like 6 is a good number, or 7 for this package, not too different.

**Comment by ateucher** [comment]
Great. How about 7, to be consistent with `geojsonio::write_json` which uses `rgdal::writeOGR` (so presumably uses GDAL's default 7)?

**Comment by sckott** [comment]
7 sounds good.
